---
title: "task1_cleaning_script"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
# cleaning variables
decathalon <- janitor::clean_names(read_rds("../raw_data/decathlon.rds"))
```

```{r}
# creating name column for row names and standardising names
decathalon <- decathalon %>% 
  tibble::rownames_to_column("name") %>%
  mutate(name = str_to_title(name))
```


Q1. Who had the longest long jump seen in the data?
```{r}
decathalon %>% 
  arrange(desc(long_jump)) %>% 
  slice_max(long_jump) %>% 
  summarise(name, long_jump)
```


Q2. What was the average 100m time in each competition?
```{r}
decathalon %>% 
  group_by(competition) %>% 
  summarise(avg_100m_time = mean(x100m))
```


Q.3 Who had the highest total points across both competitions?
```{r}
decathalon %>% 
  group_by(competition) %>% 
  slice_max(points) %>% 
  summarise(competition, name, points)
```


Q.4 What was the shot-put scores for the top three competitors in each competition?

Q.5 What was the average points for competitors who ran the 400m in less than 50 seconds vs. those than ran 400m in more than 50 seconds?

```{r}
decathalon %>% 
summary()
```


